<?php

require_once 'functions.php';

// Configure API credentials
$publicKey = 'eae4edb08be6bc3d0ce2dd464251eca3939d463aef8bbf710d6111be2281dc02';
$privateKey = 'xabc143b70e4017530e7a9f5c9b6c7f80421af7a1041024d92b2246ca906281ea';

foreach (['publicKey' => $publicKey, 'privateKey' => $privateKey] as $name => $value) {
    if (strpos($value, 'REPLACE_WITH_') === 0 || trim($value) === '')
        renderPage('Request Failed', ["Set a valid value for {$name} in example/request.php before running."], 400);
}

// change this endpoint to test different endpoints
$endpoint = 'https://authentication.php.dev/test.php';

// create the payload array with some example data
$payload = [
    'action' => 'test-authentication',
    'timestamp' => date('c'),
    'data' => [
        'reference' => 'EXAMPLE-' . date('YmdHis'),
        'note' => 'Request generated by example/request.php',
    ],
];

// encode the payload as JSON and check for errors
$payloadJson = json_encode($payload);
$payloadError = json_last_error();
if ($payloadJson === false || $payloadError !== JSON_ERROR_NONE)
    renderPage('Request Failed', ['Unable to encode payload array as JSON.'], 500);

// generate the signature using the payload and the private key
$signature = base64_encode(hash_hmac('sha256', $payloadJson, $privateKey, true));

// make the call to the endpoint with the appropriate headers and payload
$ch = curl_init($endpoint);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, [
    'Content-Type: application/json',
    'Authorization: ' . $publicKey,
    'X-Signature: ' . $signature,
]);
curl_setopt($ch, CURLOPT_POSTFIELDS, $payloadJson);

$response = curl_exec($ch);
$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
$error = curl_error($ch);
curl_close($ch);

if ($error) renderPage('Request Failed', ["cURL error: {$error}"], 500);

$json_response = json_decode($response);
if($json_response->status == 'ok') {
    
}

renderPage(
    'Request Completed',
    [
        'Target URL: ' . $endpoint,
        'HTTP ' . $httpCode,
        '',
        'Payload JSON:',
        $payloadJson,
        '',
        'Response:',
        (string) $response
    ],
    200
);
